---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webapp.shi.io
  resources:
  - entries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.shi.io
  resources:
  - entries/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.shi.io
  resources:
  - entries/status
  verbs:
  - get
  - patch
  - update
